services:
  postgres:
    image: postgres:15
    container_name: postgres-15
    restart: unless-stopped
    ports:
      - "7014:5432"
    networks:
      - shared
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: g0d1sf8f00l
      POSTGRES_DB: selfhealing

volumes:
  postgres_data:

networks:
  shared:
    external: true
